### PR TITLE
Migrate to pekko

### PR DESCRIPTION
**Pull request by TomJKing**

### CODE REVIEW

**Comment by KarelCemus** [comment]
there are significant underlying changes ongoing, I am preparing more significant changes for the next major release which migration to pekko definitely is. see https://github.com/KarelCemus/play-redis/issues/264#issuecomment-1867349965

The migration is moving forward just slower than expected but I believe I'll get through the work part soon.

Another option is that I'll release major version with pekko and then another major release with other changes, which is also an option I am considering given it takes more time than expected.

**Comment by harrylaou** [comment]
@KarelCemus Thanks for your response. 
If releasing an upgrade to pekko on its own an option, I would be grateful 🙇🏼 . 
It is the only library that is keeping me back for upgrading a project to play 3. 
If you need any help in the process, please let me know.

**Comment by KarelCemus** [comment]
Let me think it through. I didn't want to maintain branches for both play 2.9 and play 3 during those major changes, maybe I'll release a version for play 2.9  without those improvements and the major changes will land only into the version for play 3

**Comment by KarelCemus** [comment]
Merged as a part of #278 , thanks @TomJKing for this contribution

**Comment by KarelCemus** [comment]
Releasing `4.0.0-M1` for Scala 2.13.

Release for Scala 3 is blocked at this moment, see https://github.com/KarelCemus/play-redis/issues/264 for more details.

**Pull request closed without merging**
