### PR TITLE
Revamped tests

### LINKED ISSUE #108: Tests refactoring
Right now, there is about 500 tests, which are quite complex, take a long time to execute and most of them has a very little value. This issue proposes their refactoring with these goals:

 - reduce their number
 - reduce the complexity
 - reduce the execution time
 - increase their value
 - deploy mocking to deliver less of more worth tests.

### PR DESCRIPTION
**Pull request by KarelCemus**
Revamped tests fixes #108

- reduced number of tests
- increased their value
- increased code coverage
- used smaller number of unit tests with mocks instead of large number of integration test
- fixed several minor issues identified through tests

### CODE REVIEW

**Comment by KarelCemus** [comment]
@pcejrowski I've revamped tests to have better coverage. Basically, the tests now cover everything but the cluster. It is the only thing left. Do you have any experience setting up the cluster in Travis? If so, could you give me some help, please?

**Comment by pcejrowski** [comment]
Hi @KarelCemus!
I have no former experience with that but would be happy to help. I will take care of it later the following workweek. 
What am I going to do?
Replace Travis' default `redis-server` service with [grokzen/redis-cluster](https://hub.docker.com/r/grokzen/redis-cluster/)
> The cluster is 6 redis instances running with 3 master & 3 slaves, one slave for each master. They run on ports 7000 to 7005. It also contains 2 standalone instances that is not part of the cluster. They are running on port 7006 & 7007
So that, the standalone instances can be used for current tests and the cluster for the cluster-related features.

**Comment by KarelCemus** [comment]
@pcejrowski Thanks, that would be awesome if you could help. I've opened #158 for this task.

I'd be great if you could set up Travis so that we could run tests against both standalone and cluster instances. The standalone is already setup thus only the cluster is missing. If it is possible, it would be nice to integrate that grokzen/redis-cluster into Travis. It would solve all issue. I'd then implement the tests.

**Comment by KarelCemus** [comment]
> It also contains 2 standalone instances that is not part of the cluster. They are running on port 7006 & 7007

I believe we don't need these, there is already running a standalone instance

**Comment by KarelCemus** [comment]
Moving this discussion into #158.

**Pull request merged**
