### PR TITLE
Sentinel support

### PR DESCRIPTION
**Pull request by tmscer**
Support for sentinel with database and password support and doc for config.

### CODE REVIEW

**Comment by tmscer** [comment]
Fixed a syntax error. The RedisSentinelSpecs uses external Sentinel instances since I am not familiar with the way this project simulates Redis.

**Comment by KarelCemus** [comment]
Hi, thank you for your contribution. I briefly peeked at the PR and it looks good, although I might have several minor notes. However, I am leaving for a couple days off right now, so I cannot go through this PR in detail. I'll be back about mid-September and get back to this. I hope that it is alright.

Thanks for understanding

**Comment by KarelCemus** [comment]
@pcejrowski Pawel, are you able and willing to help us to configure a Docker image to run a sentinel redis, please? Unfortunately, I'm not much familiar with it.

**Comment by pcejrowski** [comment]
Hey, I will do my best to get it done by the end of this week, but I cannot promise anything.

**Comment by KarelCemus** [comment]
@pcejrowski  That would be awesome, thanks.

**Comment by pcejrowski** [comment]
I have just committed this: https://github.com/Grokzen/docker-redis-cluster/pull/51 and added https://github.com/tmscer/play-redis/pull/1, if you want to start testing earlier.

**Comment by tmscer** [comment]
What should be the connection details for the Sentinel instances? Are they on dockerIp (172.17.0.2)?

**Comment by KarelCemus** [comment]
I tried to make the tests running, however, I failed. Here is what I have done so far:

- swapped to `pcej/redis-cluster` docker container (it seems the that you PR won't be merged in near future)
- changed master-group name to `sentinel7000` in the `RedisSentinelSpecs` but it is not relevant right now
- started docker
- successfully connect to the sentinel itself via `redis-cli -p 5000 -h 172.17.0.2` and it works quite fine, at least [as far I can tell](https://redis.io/topics/sentinel)
- however, I am **unable to connect** to managed instances at 5001 and 5002 themselves. I also attached to the docker container and listed processes and ports and it seems like the instances are not running at all.

@pcejrowski  @tmscer Can any of you help me with this? Is it the issue of the sentinel as it is supposed to start them itself or is it the issue of the configuration and the instances should be started manually?

**Comment by pcejrowski** [comment]
My bad, I had a bug fixed by this commit: https://github.com/pcejrowski/docker-redis-cluster/commit/65572680ca1118b40548a24e062b3ca751fd3139.

I have just pushed a new version of `pcej/redis-cluster:latest`.

Re: 
> Note: current code is in the tmscer-sentinel branch in this repo, if you are interested.
@tmscer might allow pushing to his branch using the checkbox on the right side: `Allow edits from maintainers.`, so that those branches don't diverge.

**Comment by KarelCemus** [comment]
@pcejrowski Thank you for your great work, it sort of works right now. However, I am wondering ... some tests fail due to unexpected answer, which contains "MOVED". It seems like you have configured sentinels over cluster nodes. It might be correct, I know very little about a sentinel, but as far as i can tell, isn't more common setup over standalone nodes?

**Comment by KarelCemus** [comment]
@tmscer Merged via #185. Thank you for your contribution. 

@pcejrowski Thanks for your help. I've adjusted the docker setup but I wouldn't be able to do it myself.

**Comment by pcejrowski** [comment]
@KarelCemus Sorry for the late reply.
Unfortunately, I have no expertise in Sentinel setups. It seems that both options are reasonable (https://redis.io/topics/sentinel).

**Pull request closed without merging**
