### PR TITLE
Redis Cluster

### PR DESCRIPTION
**Pull request by KarelCemus**
Introduced support of redis cluster requested in #84.

@pcejrowski: May I ask you to review this PR? Honestly, I didn't test it because I have no configured cluster and I am kind a lazy and short on time doing (and learning) that as it does not seem actually necessary as the code seems to be simple. Could you review it or possibly test it in your environment, please?

### CODE REVIEW

**Comment by pcejrowski** [comment]
Hey, many thanks for this. I'm going to review it during next weekend.

**Comment by KarelCemus** [comment]
Hi @pcejrowski, any progress on this issue?

**Comment by pcejrowski** [comment]
Hey, 
I was unable to review it earlier, my sincere apology for this.
Unfortunately, I faced some problems with your PR: 
**No configuration setting found for key 'password'**, whereas cluster is insecure, so it shouldn't be mandatory. I **haven't** dig into `play-redis` today to figure it out. I'll take a closer look on Monday.

Here is my way to reproduce it, which shouldn't take more than 5 minutes:
### 1a. 
`docker run -i -t -p 7000:7000 -p 7001:7001 -p 7002:7002 -p 7003:7003 -p 7004:7004 -p 7005:7005 --name rcluster grokzen/redis-cluster:latest` 
### 1b. (Mac OS only) 
Prepare grokzen/redis-cluster including PR#15 and PR#24:
```
git clone git@github.com:Grokzen/docker-redis-cluster.git
```
Changes:
Dockerfile
```
-   RUN apt-get install -y gcc make g++ build-essential libc6-dev tcl git supervisor ruby
+   RUN apt-get install -y wget gcc make g++ build-essential libc6-dev tcl git supervisor ruby
```
docker-data/docker-entrypoint.sh
```
-    IP=`ifconfig | grep "inet addr:17" | cut -f2 -d ":" | cut -f1 -d " "`
+    IP=0.0.0.0
```
and run using `make compose-up && make compose-up`
### 2. 
`git clone git@github.com:KarelCemus/play-redis.git`
### 3. 
`cd play-redis && git checkout cluster && sbt publishLocal`
### 4.
`cd .. && sbt new playframework/play-scala-seed.g8 && cd play-scala-seed` - some enters are necessary here to choose default settings
### 5. 
Add sufficient dependencies:
```
libraryDependencies += play.sbt.PlayImport.cacheApi
libraryDependencies += "com.github.karelcemus" %% "play-redis" % "1.6.0-SNAPSHOT"
```
### 6. 
Update `conf/application.conf`
```
play.modules.enabled += "play.api.cache.redis.RedisCacheModule"
play.cache.redis.cluster = [
  {
    host: "127.0.0.1"
    port: 7000
  },
  {
    host: "127.0.0.1"
    port: 7001
  },
  {
    host: "127.0.0.1"
    port: 7002
  },
  {
    host: "127.0.0.1"
    port: 7003
  },
  {
    host: "127.0.0.1"
    port: 7004
  },
  {
    host: "127.0.0.1"
    port: 7005
  }
]
```
### 7. 
Insert data to redis cluster:
```
$ redis-cli -c -p 7000
127.0.0.1:7000> set x 1
-> Redirected to slot [16287] located at 127.0.0.1:7002
OK
```
### 8. 
Inject CacheApi in HomeController and read x from redis cache:
```
package controllers

import javax.inject._
import play.api.mvc._
import play.api.cache.redis.CacheApi

@Singleton
class HomeController @Inject()(cc: ControllerComponents,  cache: CacheApi ) extends AbstractController(cc) {

  def index() = Action { implicit request: Request[AnyContent] =>
    Ok(views.html.index(cache.get[String]("x").getOrElse("wrong")))
  }
}
```
### 9. 
Edit index.scala.html to include value from Redis:
```
@(xvalue: String)

@main("Welcome to Play") {
  <h1>Welcome to Play!</h1>
  <h2>@xvalue</h2>
}
```
### 10. 
Run app: `sbt run` and go to: `localhost:9000`
I’ve got an error:
1) Error injecting constructor, com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'password'

**Comment by KarelCemus** [comment]
Wow, awesome! Thanks for the detailed manual how to reproduce it. I really appreciate it, thanks!  

I'll fix the PR and let you know.

**Comment by pcejrowski** [comment]
I forced it to work adding `password` and `database` parameters to cluster configuration, so that `config/application.conf` looks like this:
```
play.modules.enabled += "play.api.cache.redis.RedisCacheModule"
play.cache.redis.cluster = [
  {
    host: "127.0.0.1"
    port: 7000
    password = ""
    database = 0
  },
  {
    host: "127.0.0.1"
    port: 7001
    password = ""
    database = 0
  },
  {
    host: "127.0.0.1"
    port: 7002
    password = ""
    database = 0
  },
  {
    host: "127.0.0.1"
    port: 7003
    password = ""
    database = 0
  },
  {
    host: "127.0.0.1"
    port: 7004
    password = ""
    database = 0
  },
  {
    host: "127.0.0.1"
    port: 7005
    password = ""
    database = 0
  }
]
```
* database no. 0 is taken by default when using `reds-cli`

**Comment by pcejrowski** [comment]
The problem is in `play.api.cache.redis.configuration.ConfigurationFile` lines: 45-46, because, method: `com.typesafe.config.Config#getIsNull` do `Checks whether a value is set to null at the given path, but throws an exception if the value is entirely unset.` so, unless you want to add some default cluster, which you probably don't, you have to use `hasPathOrNull`, following the scaladocs:
```
     * if (config.hasPathOrNull(path)) {
     *     if (config.getIsNull(path)) {
     *        // handle null setting
     *     } else {
     *        // get and use non-null setting
     *     }
     * } else {
     *     // handle entirely unset path
     * }
```

**Comment by pcejrowski** [comment]
I've created PR #111 which fixes this. I tested Play-Redis including #111 and it works well with clustering. Many thanks for this feature.

**Comment by KarelCemus** [comment]
Awesome work @pcejrowski. Yesterday, I reproduced the error following your guide and today I wanted to fix it. However, you were faster and did a great job, thanks for that!

By the way, I am in a process of rewriting play-redis into version `2.x.x` due to several issues but mostly due to #106.  Would you mind to review it when it's ready? Right now, I think I have a solid milestone implementing #106 but with still several issues left. The thing I am worried about is a configuration, it needs to be simple but powerful, which is a bit tricky.

**Comment by pcejrowski** [comment]
Sure!

**Pull request merged**
