### PR TITLE
Advanced asynchronous Java API

### LINKED ISSUE #206: Advanced CacheAPI for Java
as you documented, play-redis implements advanced redis feather in scala,but java not,could you please implement those under java? Thank you very much.

### PR DESCRIPTION
**Pull request by KarelCemus**
Fixes #206

### CODE REVIEW

**Comment by KarelCemus** [comment]
@ourgit I implemented async Java API for you. Could you review this PR and **test it**? I am not familiar with Java version of Play nor with your use case. Could you tell if this is working and fits your needs?

**Comment by ourgit** [comment]
@KarelCemus thank you for your reply, i will review & test, and report the result to you. By the way, redis lock method  is wide used for distributed platform, do you have interesting to add the feather? Have a look at this repo:
 https://github.com/thibaultmeyer/play-redis-module

**Comment by KarelCemus** [comment]
Well, this module implements redis as a cache, I am not sure that having a lock within cache api is a good approach. The scope of this module is not to provide general redis api, there already are various libraries

**Comment by KarelCemus** [comment]
Any progress on this issue?

**Pull request merged**
