### PR TITLE
Components for Compile time DI

### LINKED ISSUE #78: Support for compile time DI
Any pointers on how to use this without DI would be helpful.

### PR DESCRIPTION
**Pull request by KarelCemus**
This PR introduces `RedisCacheComponents` components to support users with compile-time DI [fixes #78]

@asheshambasta: Could you take a look at this PR and check if it fits your needs and best-practices for compile-time DI? I'm not much familiar with that. It would be very nice if you could test it in practice.

### CODE REVIEW

**Comment by rmmeans** [comment]
I didn't do an in-depth review since we're not using this library yet, but I think this PR looks good.🎉   

---
I have contributed in the past to Lightbend's old redis play-plugin (https://github.com/playframework/play-plugins/tree/master/redis) which I had to move to here to keep maintaining: (https://github.com/lifeway/play-redis)  -- 

Great work on this library so far 👍  - I plan on deprecating the one I am maintaining and switching to this one in the future. 

If compile time DI still isn't quite sorted out when we switch, I can help contribute as we exclusively use compile time DI.

**Comment by asheshambasta** [comment]
Same as @rmmeans for me, LGTM but I couldn't do an in-depth test _yet_.

**Comment by KarelCemus** [comment]
Thanks to both of you. Then, I'll merge it into the master but keep it as a SNAPSHOT for a while to give an opportunity to test it before the release. I hope it works for you. If you test it, let me know even when it works just to know. Thanks.

**Comment by asheshambasta** [comment]
@KarelCemus thanks! But I can't seem to find the tag here https://github.com/KarelCemus/play-redis/tags or am I missing something?

**Comment by KarelCemus** [comment]
Sure you can't. It is not released yet. It is just a snapshot.

1. Enable Sonatype snapshots resolver (probably already enabled)
2. Link `libraryDependencies += "com.github.karelcemus" %% "play-redis" % "1.3.2-SNAPSHOT"`

**Comment by asheshambasta** [comment]
By bad, sorry about that.

**Pull request merged**
