### PR TITLE
[WIP] `getOrFuture` should return the value and then set cache

### PR DESCRIPTION
**Pull request by guizmaii**
Hi,

I made some optimizations:
 - `getOrFuture` does not need to wait the cache to be set thanks to `andThen`.
 - `extends AnyVal` will remove some useless instantiations.

Tell me what you think 🙂

PS: tests don't pass but I don't understand why and it seems that they don't pass neither oon your master branch. Any info on that ?

### CODE REVIEW

**Comment by KarelCemus** [comment]
Hi Jules, thanks for your contribution. I browsed the code and if I am not wrong, you propose basically 3 improvements, right?

> `getOrFuture` does not need to wait the cache to be set thanks to `andThen`.

Well, if I get it right, [`andThen`](http://www.scala-lang.org/api/current/scala/concurrent/Future.html#andThen[U](pf:PartialFunction[scala.util.Try[T],U])(implicitexecutor:scala.concurrent.ExecutionContext):scala.concurrent.Future[T]) does not propagate the result including a failure. I am affraid it conflicts with [`RecoveryPolicy`](https://github.com/KarelCemus/play-redis#recovery-policy) because there are cases (and users but I cannot find it right now) where it is required to fail the future when the communication to cache fails. With `andThen` this won't be possible. However, I might make there a configurable switch which behavior to use.

> `extends AnyVal` will remove some useless instantiations.

I have never heard of this being some kind of optimization. Could you give me a link where it is explained?

> IMHO, `RedisException` should not be sealed because the user of your lib may want to catch it too.

I do not see an issue with having it sealed. It does not prevent you catching it. It only prevents you from subtyping it, which I think is correct. Furthermore, it eases pattern matching.

**Comment by guizmaii** [comment]
Hi,

You're right about `sealed RedisException`, my bad. Sorry. I'll correct that.

About the `AnyVal` optimization, you could read the Scala documentation here: http://docs.scala-lang.org/overviews/core/value-classes.html

And about the `andThen` and the need to fail in some cases, you're again right. I'll look for a solution.

**Comment by guizmaii** [comment]
Maybe, a better solution to not breaks compatibility and RecoveryPolicies is to create a new method. What do you think ?

**Comment by KarelCemus** [comment]
I don't think the `getOrFutureWithAsyncCache` would be a solution, you are still facing the issue of the policy - you still have to deal with it or break it, some how.

I think that the better solution is to consider it within the policy itself, i.e., some policies could improve the performance by assuming a positive result (or ignoring the failure, to be more precise). For example, using `RecoverWithDefault` policy would lead to ignoring the failure, thus it is not necessary to wait for `set`. Moreover, the solution could be considered directly within `set` operation, which would indirectly affect both `getOrFuture` and `getOrElse` operations.

Finally, it wouldn't break tests as the result would be a success anyway.

What do you think?

**Comment by KarelCemus** [comment]
Thanks for the link to value classes. Very interesting reading I didn't know about. You made a good point, this would optimize it a bit. However, I've read some more discussions and it seems like it's not much worth it because we are dealing with string parsing, serialization into a string, and heavy network communication etc., while this optimization actually works (is measurable) with very lightweight computation. See [this](https://groups.google.com/forum/#!topic/scala-user/XdQnbcs2SRM).

I'll accept it and modify the code eventually but I'm not much sure it is worth the efforts.

**Comment by KarelCemus** [comment]
Hi, as this PR seems stuck and Travis still fails, I've extracted several of your proposals into #97. 

I've opened #98 dealing with your proposal of not waiting for the result of the `set` operation.

I hope I covered all your proposals so I am closing the issue. If I've missed anything, please, remind it. 

Thanks for your contribution.

**Comment by guizmaii** [comment]
Sorry for the lack of work on this subject. I'll try to take time to finish my work next week.

Thanks again for your great work and help !

**Pull request closed without merging**
